# Generated by Django 2.2.5 on 2019-10-12 09:57

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=shop.models.upload_product),
        ),
    ]
