# Generated by Django 2.2.7 on 2019-12-04 06:52

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=shop.models.upload_category),
        ),
    ]
